### ISSUE TITLE
spicetify cli web page doesn't exist

### ISSUE THREAD

**Issue by Daivy03** [grasonchan/spotify-spice#12]
Sorry for this issue but i can't find the spicetify-cli command. 
This page doesn't work:
https://spicetify.app/docs/getting-started/simple-installation
![image](https://user-images.githubusercontent.com/75785698/184220529-7ef5e365-4ff5-4c33-ab94-f79ccccb3e1a.png)

**Comment by grasonchan** [comment]
@Daivy03 

Follow [this link](https://spicetify.app/docs/getting-started) to install Spicetify CLI and Marketplace, then jump to Step 2 of the Installation.

This Issue will be fix in https://github.com/grasonchan/spotify-spice/pull/11.
