### ISSUE TITLE
No controls or exit in turntable mode

### ISSUE THREAD

**Issue by 7larson** [grasonchan/spotify-spice#8]
Hi! Once I actually click to use the turntable mode it seems like there's no controls as shown in the screenshots - no pause/play or forward and backward. Additionally, no button I press on my keyboard (and no menu option) exits turntable mode, so my only option to get out of it and navigate to another playlist is to completely restart Spotify. Not sure if this is intended?

Screenshot of the issue below. I'm on Windows 10 using the latest version of both Spotify & Spicetify.

![image](https://user-images.githubusercontent.com/43255525/121469753-aa002600-c982-11eb-80f6-672e839abaa0.png)

**Comment by grasonchan** [comment]
Refer to the [Full App Display](https://github.com/khanhas/spicetify-cli/wiki/Extensions#full-app-display).

> While in display mode, double click anywhere to exit. Right click anywhere to open setting menu.

**Comment by grasonchan** [comment]
@7larson Hi, is there a problem with the turntable rotation?

Because i tested it on Windows 10, there was a problem with the turntble ratation when swiching the playing state.
