### ISSUE TITLE
Rotate Turntable Issue

### ISSUE THREAD

**Issue by JasonTuyen** [grasonchan/spotify-spice#9]
Hello, when I attempt to install this theme there are two errors: "color.ini" and "rotateTurntable,js" are not found. Earlier issue shows that "color.ini" is not needed so I guess the real issue is "rotateTurntable,js" file is missing causing no rotation.

I am running Spicetify 2.5 and Spotify 1.1.62.583.gdac868ed-a as well as Windows 10.

**Comment by grasonchan** [comment]
Hi. Did you copy the `rotateTurntable.js` to the `Extensions` floder?

**Comment by JasonTuyen** [comment]
That fixed the issue. Thank you!
